<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>录入参赛选手</title>
    <link rel="stylesheet" href="/static/element-ui@2.13.0/css/index.css">
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
<div id="app" v-cloak>




</div>
</body>
</html>
<script src="/static/js/jquery-3.3.1.min.js"></script>
<script src="/static/js/vue.js"></script>
<script src="/static/element-ui@2.13.0/js/index.js"></script>
<script src="/static/js/echarts.min.js"></script>
<script>
    Vue.prototype.$ELEMENT = { size:'mini', zIndex: 3000 };          //设置主题字号和按钮
</script>

<script>
    var vm = new Vue({
        el: '#app',
        data:{

        },
        methods: {

        },
        mounted:function () {
            this.init(0);
        },
    })
</script>