</el-container>
</el-container>
</el-container>
</div>
</body>
</html>
<script src="/static/js/vue.js"></script>
<script src="/static/element-ui@2.13.0/js/index.js"></script>
<script src="/static/js/echarts.min.js"></script>
<script>
    Vue.prototype.$ELEMENT = { size:'mini', zIndex: 3000 };          //设置主题字号和按钮
    Vue.component("childMenu",{template:'#menu',props:['dataList']}); //注册一个menu组件，主要用来实现无限极下拉菜单
</script>