<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/element-ui@2.13.0/css/index.css">
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
<div id="app" v-cloak>
    <el-container class="wrapper">
        <el-header>
            <div class="logo">hello</div>
            <div class="head-right">
                <div class="search">33333</div>
            </div>
        </el-header>

        <el-container class="main-wrapper">
            <?php Yaf\Loader::import(__DIR__.'/aside.phtml');?>
            <el-container>