<script>
    var vm = new Vue({
        el: '#app',
        data:<?php echo json_encode($view['form']);?>,
        methods: {
            submitForm(formName) {
                this.$refs[formName].validate((valid) => {
                    if (valid) {
                        alert('submit!');
                    } else {
                        console.log('error submit!!');
                        return false;
                    }
                });
            },
        }
    })
</script>