<?php Yaf\Loader::import(__DIR__.'/../head.phtml');?>
<el-main>
    <?php Yaf\Loader::import(__DIR__.'/../breadcrumb.phtml');?>
    <div class="table-list">
        <el-button style="margin-bottom: 20px" type="primary" @click="dialog=true">添加</el-button>
        <!--通用表格-->
        <?php Yaf\Loader::import(__DIR__.'/../table.phtml');?>
        <!--通用的表单-->
        <?php Yaf\Loader::import(__DIR__.'/../form.phtml');?>
    </div>
</el-main>
<?php Yaf\Loader::import(__DIR__.'/../foot.phtml');?>
<!--通用的JS-->
<?php Yaf\Loader::import(__DIR__.'/../js.phtml');?>
